### ISSUE TITLE
Docker Image can not scan rpm based OS

### ISSUE THREAD

**Issue by nagyclaudiu83** [bitnami/bitnami-docker-harbor-adapter-trivy#1]
**Description**

An installation of Bitnami Harbor version 2.0.0 with trivy as the only vulnerability scanner fails to produce results for rpm based docker images (tested on CentOS only). 

**Steps to reproduce the issue:**

1. Deploy Bitnami Harbor 2.0.0 with Trivy Scanner
2. Push a CentOS image to the repository
3. Scan the Image for Vulnerabilities

**Describe the results you received:**

The Scan Report shows a "View Log" error message with the error:
FATAL error in image scan: failed analysis: analyze error: failed to analyze layer: sha256:8631ace4f24df304c165865d38bc9599c3ecfc795c1993b28fcd707b244664f2 : failed to get packages: failed to get packages: failed to parse the pkg info: no rpm command

**Describe the results you expected:**

View the Vulnerabilities of the docker image

**Additional information you deem important (e.g. issue happens only occasionally):**
This issue from trivy might explain it as the bitnami image is missing the rpm command.
-- https://github.com/aquasecurity/trivy/issues/146

**Version**
Trivy docker image is: docker.io/bitnami/harbor-adapter-trivy:2.0.0-debian-10-r7

Harbor running under Rancher Deployed Kubernetes version 1.17.6 , OS CentOS 7.7 , Docker 19.3.8 .

**Comment by miguelaeh** [comment]
Hi @nagyclaudiu83 ,
Thank you very much for reporting this issue.
It seems that we need to add `rpm` to this image.

**Comment by miguelaeh** [comment]
Hi @nagyclaudiu83 ,
We addressed the issue internally and `rpm` has been added to the image in this commit: https://github.com/bitnami/bitnami-docker-harbor-adapter-trivy/commit/65cf39d726ddd4c40c0361b93354903dc1d06385

**Comment by nagyclaudiu83** [comment]
Thank you for the quick response.
I have deployed docker.io/bitnami/harbor-adapter-trivy:2.0.0-debian-10-r12 version and i can confirm that i can now scan CentOS container images and probably other rpm based distributions are also fixed.
